"""
Django settings for Reconcile project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from datetime import timedelta
import environ
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Initialize environment variables
env = environ.Env()
environ.Env.read_env(env_file=os.path.join(BASE_DIR, '.env'))

APP_NAME = env('APP_NAME')

SECRET_KEY = env('SECRET_KEY')

DEBUG = env.bool('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS')
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS')
CORS_ALLOW_CREDENTIALS = True


SMTP_HOST = env('SMTP_HOST')
SMTP_PORT = env.int('SMTP_PORT')
SMTP_USERNAME = env('SMTP_USERNAME')
SMTP_PASSWORD = env('SMTP_PASSWORD')


MEDIA_ROOT = env('MEDIA_ROOT')
MEDIA_URL = env('MEDIA_URL')

AUTH_USER_MODEL = 'accounts.User'

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',
    'drf_spectacular',
    
    # Local apps
    'apps.accounts',
    'apps.normalization',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "drf_commons.middlewares.current_user.CurrentUserMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': env.db('DATABASE_URL')
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"


# Rest Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'core.authentication.CookieJWTAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'drf_commons.filters.ComputedOrderingFilter',
    ),
    'DEFAULT_PAGINATION_CLASS': 'drf_commons.pagination.StandardPageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

GUEST_COOKIE_NAME = env("GUEST_COOKIE_NAME")
GUEST_COOKIE_MAX_AGE = env.int("GUEST_COOKIE_MAX_AGE")

NORMALIZE_SERVICE_URL = env("NORMALIZE_SERVICE_URL")
WEBHOOK_BASE_URL = env("WEBHOOK_BASE_URL")
NORMALIZE_SUGGESTION_METHOD = env("NORMALIZE_SUGGESTION_METHOD")
NORMALIZE_EXTENDED_TYPE_DETECTION = env.bool("NORMALIZE_EXTENDED_TYPE_DETECTION")

S3_ENDPOINT_URL = env("S3_ENDPOINT_URL")
S3_ACCESS_KEY_ID = env("S3_ACCESS_KEY_ID")
S3_SECRET_ACCESS_KEY = env("S3_SECRET_ACCESS_KEY")
S3_BUCKET_NAME = env("S3_BUCKET_NAME")
S3_REGION = env("S3_REGION", default="auto")

UPLOAD_MAX_FILE_SIZE_MB = {
    "csv":  env.int("UPLOAD_MAX_CSV_FILE_SIZE_MB"),
    "xlsx": env.int("UPLOAD_MAX_XLSX_FILE_SIZE_MB"),
    "json": env.int("UPLOAD_MAX_JSON_FILE_SIZE_MB"),
}

DUCKDB_EXPORT_MEMORY_LIMIT = env("DUCKDB_EXPORT_MEMORY_LIMIT")
DUCKDB_EXPORT_THREADS = env.int("DUCKDB_EXPORT_THREADS")

# Celery
CELERY_BROKER_URL        = env("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND    = env("CELERY_RESULT_BACKEND")
CELERY_ACCEPT_CONTENT    = ["json"]
CELERY_TASK_SERIALIZER   = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE          = TIME_ZONE

# Cache configuration using Redis
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": env("CACHE_URL"),
    }
}


SPECTACULAR_SETTINGS = {
    'TITLE': APP_NAME,
    'DESCRIPTION': f'API documentation for {APP_NAME}',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'PATH_PREFIX': 'api',
}


# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
# One rotating file per concern, all living under <project>/logs, plus a
# console stream (so `docker compose logs` / `manage.py runserver` still work).
#
#   logs/app.log       root / third-party libraries (boto3, urllib3, ...)
#   logs/business.log  our domain code (apps.*, normalize, export, core)
#   logs/django.log    the Django framework
#   logs/request.log   HTTP 4xx/5xx handled by django.request
#   logs/security.log  django.security (host header, CSRF, ...)
#   logs/sql.log       raw SQL (only when LOG_SQL=true)
#   logs/celery.log    Celery worker & tasks
#   logs/error.log     every ERROR/CRITICAL from anywhere, aggregated
#
# Tunables (env):  LOG_LEVEL (default INFO), LOG_SQL (default false),
#                  LOG_TO_CONSOLE (default true), LOG_MAX_BYTES, LOG_BACKUP_COUNT.
LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(parents=True, exist_ok=True)

LOG_LEVEL = env("LOG_LEVEL", default="INFO").upper()
LOG_SQL = env.bool("LOG_SQL", default=False)
LOG_TO_CONSOLE = env.bool("LOG_TO_CONSOLE", default=True)
LOG_MAX_BYTES = env.int("LOG_MAX_BYTES", default=10 * 1024 * 1024)  # 10 MB
LOG_BACKUP_COUNT = env.int("LOG_BACKUP_COUNT", default=10)


def _file_handler(filename, *, level="NOTSET", formatter="verbose"):
    """A size-rotated file handler under LOG_DIR (opened lazily on first write)."""
    return {
        "level": level,
        "class": "logging.handlers.RotatingFileHandler",
        "filename": str(LOG_DIR / filename),
        "maxBytes": LOG_MAX_BYTES,
        "backupCount": LOG_BACKUP_COUNT,
        "encoding": "utf-8",
        "delay": True,
        "formatter": formatter,
    }


# Handlers every domain logger shares: its own file + the console + the
# aggregated error file. Keeps each logger definition to one line below.
def _channel(own_file):
    handlers = [own_file, "error_file"]
    if LOG_TO_CONSOLE:
        handlers.insert(0, "console")
    return handlers


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        # Aligned, pipe-separated columns — easy to scan and easy to grep.
        "verbose": {
            "()": "logging.Formatter",
            "format": "{asctime} │ {levelname:<8} │ {name:<26} │ {module}:{lineno} │ pid:{process} │ {message}",
            "datefmt": "%Y-%m-%d %H:%M:%S %z",
            "style": "{",
        },
        "concise": {
            "()": "logging.Formatter",
            "format": "{asctime} │ {levelname:<8} │ {name} │ {message}",
            "datefmt": "%H:%M:%S",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": LOG_LEVEL,
            "class": "logging.StreamHandler",
            "formatter": "concise",
        },
        "app_file": _file_handler("app.log", level=LOG_LEVEL),
        "business_file": _file_handler("business.log", level="DEBUG"),
        "django_file": _file_handler("django.log", level="INFO"),
        "request_file": _file_handler("request.log", level="WARNING"),
        "security_file": _file_handler("security.log", level="INFO"),
        "sql_file": _file_handler("sql.log", level="DEBUG"),
        "celery_file": _file_handler("celery.log", level="INFO"),
        # Aggregated errors from every logger; always full detail.
        "error_file": _file_handler("error.log", level="ERROR"),
    },
    "root": {
        "level": LOG_LEVEL,
        "handlers": (["console"] if LOG_TO_CONSOLE else []) + ["app_file", "error_file"],
    },
    "loggers": {
        # --- Django framework ---
        "django": {"level": "INFO", "handlers": _channel("django_file"), "propagate": False},
        "django.request": {"level": "WARNING", "handlers": _channel("request_file"), "propagate": False},
        "django.security": {"level": "INFO", "handlers": ["security_file", "error_file"], "propagate": False},
        "django.db.backends": {
            "level": "DEBUG" if LOG_SQL else "WARNING",
            "handlers": ["sql_file"],
            "propagate": False,
        },
        # --- Celery ---
        "celery": {"level": "INFO", "handlers": _channel("celery_file"), "propagate": False},
        # --- Our domain code ---
        "apps": {"level": LOG_LEVEL, "handlers": _channel("business_file"), "propagate": False},
        "normalize": {"level": LOG_LEVEL, "handlers": _channel("business_file"), "propagate": False},
        "export": {"level": LOG_LEVEL, "handlers": _channel("business_file"), "propagate": False},
        "core": {"level": LOG_LEVEL, "handlers": _channel("business_file"), "propagate": False},
    },
}

# Let our LOGGING config own the loggers instead of Celery hijacking root.
CELERY_WORKER_HIJACK_ROOT_LOGGER = False
